name: Publish package
on:
    push:
        branches:
            - master
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - uses: JS-DevTools/npm-publish@v2
              with:
                  node-version: 16.x
                  token: ${{ secrets.NPM_TOKEN }}
            - run: npm test
