name: Publish package
on:
    push:
        branches:
            - master
jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - name: Publish if version has been updated
              uses: pascalgn/npm-publish-action@1.3.8
              with:
                  node-version: 16.x
                  token: ${{ secrets.NPM_TOKEN }}
            - run: npm test
